language: python

python:
  # CPython:
  - "2.7"
  - "3.3" # but allowed to fail
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # TODO: change to "3.7" once it gets released
  - "nightly"
  # PyPy:
  - "pypy"
  - "pypy3"

os:
  - linux   # Linux is officially supported and we test the library under
            # many different Python verions (see "python: ..." above)

# - osx     # OSX + Python is not officially supported by Travis CI as of Feb. 2018
            # nevertheless, "nightly" and some "*-dev" versions seem to work, so we
            # include them explicitly below (see "matrix: include: ..." below)

# - windows # Windows is not supported at all by Travis CI as of Feb. 2018

# Linux setup
dist: trusty
sudo: false

matrix:
  # see "os: ..." above
  include:
    - os: osx
      python: "3.6-dev"
    - os: osx
      python: "3.7-dev"
    - os: osx
      python: "nightly"

  allow_failures:
    # allow all nighly builds to fail, since these python versions might be unstable
    - python: "nightly"

    # we do not allow dev builds to fail, since these builds are considered stable enough

    # Python 3.3 tests are allowed to fail since Python 3.3 is not offically supported any more
    - python: "3.3"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libffi-dev pkg-config

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash test/open_vcan.sh ; fi
  - travis_retry pip install .[test]

  # install micropython, see https://github.com/micropython/micropython#the-unix-version
  - cd ..
  - git clone https://github.com/micropython/micropython.git
  - cd micropython
  - git submodule update --init
  - cd ports/unix
  - make axtls
  - make
  - sudo make install
  - cd ../../../python-can
  - micropython -m upip install .
  - micropython -m upip install mock nose pytest-timeout pyserial

script:
  - py.test -v --timeout=300
  - micropython -m pytest -v --timeout=300
